// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recibos.Model;

namespace Recibos.Model.Migrations
{
    [DbContext(typeof(RecibosContext))]
    partial class RecibosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("Recibos.Model.Recibo", b =>
                {
                    b.Property<int>("ReciboId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ServicoData");

                    b.Property<string>("ServicoDescricao");

                    b.Property<string>("ServicoValor");

                    b.Property<string>("TomadorCpf");

                    b.Property<string>("TomadorNome");

                    b.HasKey("ReciboId");

                    b.ToTable("Recibos");
                });
#pragma warning restore 612, 618
        }
    }
}
